spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
  profiles:
    active: test
  http:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-file-size: 10Mb
      max-request-size: 100MB
  redis:
    #cluster:
      #nodes: 192.168.150.30:7000,192.168.150.30:7001,192.168.150.30:7002,192.168.150.30:7003,192.168.150.30:7004,192.168.150.30:7005,192.168.150.30:7006
    port: 7000
    database: 0
    host: 192.168.234.30
    pool:
     max-wait: -1
     max-active: 8
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
server:
  jsp-servlet:
    init-parameters:
      development: true
  context-path: /springboot