
spring:
  datasource:
    url: jdbc:mysql://192.168.234.13:8066/aaa
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
server:
  jsp-servlet:
    init-parameters:
      development: true