server:
  port: 8989
  context-path: /ems11
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zsl
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/dao/*Mapper.xml